### ISSUE TITLE
Negative Prices

### ISSUE THREAD

**Issue by tibz64** [cmdty/storage#17]
Hi,

I am trying to use the 3 factor model to simulate random hourly electricity price cuves based on a volatility curve and a forward curve. However my forward curve has négative prices…which is not allowed in the model.
Do you know how I can deal with this issue?

thanks

**Comment by cmdty** [comment]
I can think of a hacky way to allow negative prices. The multifactor model used is lognormal, so no negative prices are assumed not to be allowed. So to fudge the model to allow negative prices you need to then adjust the inputs such that the forward curve you input is not actually the forward price, but actually the forward price minus the minimum allowable price. So this assumes that forward prices are shifted-lognormal, the price + a constant is lognormal. For example if you say that the minimum price floor is -12.5, then the model (with hacked inputs) assumes that the price - (-12.5) is lognormal. The problem with this is that you then have to hack the inject/withdraw costs to adjust the cashflow to take into account the difference between the forward curve you feed in, and what the actual prices should be.
1. Choose a price floor, i.e. the minimum price that should be allowed which in your case will be negative. This can be time-varying.
2. Take your forward curve input and subtract the price floor, i.e. add the absolute value of the price floor.
3. The problem now is that the spot prices simulated by the model aren't actually spot prices, they are the spot prices plus the absolute value of the price floor, hence the cash flows from injection and withdrawal will be wrong. The inject/withdraw cost can be used to adjust for this be subtracting or adding the difference between the simulated spot price and the actual price. This difference will be the price floor.
4. Finally you will need to adjust the vols fed into the model to take into account that the model is simulating the spot price plus a constant. This will be a bit complicated, but something with moment matching could work.

Another more advanced thing you could to is just create your own spot price simulator code, which follows whatever process you want, and use this for the valuation. This is possible with the C# API, but not the Python API yet. When creating and instance of LsmcValuationParameters<T>.Builder, instead of calling SimulateWithMultiFactorModelAndMersenneTwister or SimulateWithMultiFactorModel to create the builder with a multi-factor simulator you can assign to the builder properties RegressionSpotSimsGenerator and ValuationSpotSimsGenerator delegates which return the simulated price under whatever model you choose to implement.
