### ISSUE TITLE
Mean reversion for three-factor seasonal model 

### ISSUE THREAD

**Issue by nribei** [cmdty/storage#34]
Hello, 
I would like to understand how to calculate the mean reversion as I dont understand the figure you use in your exemple (mean reversion = 91)
When I used the Ornstein-Uhlenbeck for my historical spot prices, I obtained alfa = 0.017 and average = 35.76. 

What does this 91 represent in your example?  How do you calculate it ?

Many thanks

**Comment by cmdty** [comment]
@nribei, the 3-factor model is roughly based on [this model](https://www.kyos.com/wp-content/uploads/2016/06/JEM_De_Jong_Boogert_2012.pdf). Page 9 gives a brief description of how the parameters (including the mean reversion you mention) should be calibrated. The previous paper makes reference to [this paper](https://www.kyos.jp/wp-content/uploads/sites/2/2016/09/Cointegration-between-gas-and-power-spot-prices-JEM-2009-De-Jong-Scheider.pdf) which says more about calibrating the mean reversion.

Here is a summary of how the params are calibrated according to these 2 papers:
-	Long-term vol parameter: annualized standard deviation of log returns of a whole year contract at the back of the curve.
-	Seasonal vol parameter: annualized standard deviation of Q1-Q3 (for some year in middle of curve) series, divided by 0.9.
-	Spot vol and mean reversion; do an autoregression of log spot price (adjusted to strip out seasonal and long-term vol effects) around the log of month-ahead (probably adjusted in same way), with mean reversion spot vol coming out as estimated parameters of this.

You'll see from the last point that the mean reversion in the 3-factor model, is not the mean reversion of the raw spot prices as you have calculated, but the mean reversion of of the spot price factor, driving the curve. This will explain some of the difference between your number and the example figure of 91. Another probably reason for the difference is that the model mean reversion is annualised, which means you will need to multiply a statistically inferred mean reversion by the number of days per year assumed.

**Comment by nribei** [comment]
Hello, 
Thanks for your help !

I tried to code it, but I have strange result :
Long-term volatility: 0.436
Seasonal volatility: 11.15
Spot volatility: 0.115
Mean reversion: -0.886

Sheets :
Prix CAL = yearly contract for year 25
Prix  spot = spot price and month-ahead price
Prix Q1-Q3 = difference between Q125 and Q324 price

Below is my code : 
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg

# Load in the Excel spreadsheet
input_data = pd.ExcelFile("XXX")

# Load the individual sheets into pandas dataframes
prix_cal = input_data.parse('Prix CAL')
q1_q3 = input_data.parse('Prix Q1-Q3')
spot = input_data.parse('Prix spot')

# Calculate the long-term volatility by finding the annualized standard deviation of the log returns
prix_cal['Log Return'] = np.log(prix_cal['CAL'] / prix_cal['CAL'].shift(1))
long_term_volatility = np.std(prix_cal['Log Return']) * np.sqrt(252)

# Calculate the seasonal volatility by finding the annualized standard deviation of the Q1-Q3 spread
q1_q3['Log Return']= np.log(q1_q3['Q1-Q3'] / q1_q3['Q1-Q3'].shift(1))
seasonal_volatility = np.std(q1_q3['Log Return']) * np.sqrt(252) / 0.9

# Calculate adjusted log spot price and adjusted log month-ahead price
log_spot_price = np.log(spot['Spot Price'])
log_month_ahead_price = np.log(spot['Month Ahead Price'])
adjusted_log_spot_price = log_spot_price - long_term_volatility - seasonal_volatility
adjusted_log_month_ahead_price = log_month_ahead_price - long_term_volatility - seasonal_volatility

# Fit a simple autoregressive model with log spot price as the dependent variable and log month ahead price as the independent variable
model = AutoReg(adjusted_log_spot_price, lags=1, exog=adjusted_log_month_ahead_price)
results = model.fit()

# Calculate spot volatility and mean reversion
spot_volatility = np.sqrt(results.sigma2)
mean_reversion = -results.params[1]

print(f'Long-term volatility: {long_term_volatility}')
print(f'Seasonal volatility: {seasonal_volatility}')
print(f'Spot volatility: {spot_volatility}')
print(f'Mean reversion: {mean_reversion}')

Attached is my excel file. 
[paramètres pour help.xlsx](https://github.com/cmdty/storage/files/12686805/parametres.pour.help.xlsx)

Do you see why ? 

Many Thanks for your help :)

**Comment by cmdty** [comment]
I won't have time to look at this properly until the weekend. Having taken a quick look at it now, you've made a good start, but there is definitely an issue with the way you are adjusting the spot price series with "adjusted_log_spot_price = log_spot_price - long_term_volatility - seasonal_volatility". When adjusting the spot prices/returns it is actually be subtracting movements caused by the long term and seasonal factor. The seasonal adjustment is a bit complicated so I'll ignore that for now. But I would subtract the log returns of the long-term price from the log returns of the spot price before doing the auto-regression. But that is contrary to the 2nd paper where regression isn't on returns by outright prices. So maybe just subract the log long term price from the log spot price.

**Comment by nribei** [comment]
Hello, 
Thanks for your time and help !

here is the modification I tried to do : 

input_data = pd.ExcelFile("XX")

prix_cal = input_data.parse('Prix CAL')
q1_q3 = input_data.parse('Prix Q1-Q3')
spot = input_data.parse('Prix spot')

seasonal_volatility = np.std(q1_q3['Q1-Q3']) * np.sqrt(252) / 0.9

prix_cal["Log_Return_CAL"] = np.log(prix_cal["CAL"] / prix_cal["CAL"].shift(1))
spot["Log_Return_Spot"] = np.log(spot["Spot Price"] / spot["Spot Price"].shift(1))

prix_cal['Log Return'] = np.log(prix_cal['CAL'] / prix_cal['CAL'].shift(1))
long_term_volatility = np.std(prix_cal['Log Return']) * np.sqrt(252)

spot["Adjusted_Log_Spot"] = spot["Log_Return_Spot"] - prix_cal["Log_Return_CAL"]

adjusted_log_month_ahead_price = np.log(spot["Month Ahead Price"].clip(lower=0.0001))

adjusted_log_spot_price_valid = spot["Adjusted_Log_Spot"][np.isfinite(spot["Adjusted_Log_Spot"]) & np.isfinite(adjusted_log_month_ahead_price)]

model = AutoReg(adjusted_log_spot_price_valid, lags=1, exog=adjusted_log_month_ahead_price.loc[adjusted_log_spot_price_valid.index])
results = model.fit()


spot_volatility = np.sqrt(results.sigma2)
mean_reversion = -results.params[1]

print(f'Long-term volatility: {long_term_volatility}')
print(f'Seasonal volatility: {seasonal_volatility}')
print(f'Spot volatility: {spot_volatility}')
print(f'Mean reversion: {mean_reversion}')


I obtain this result : 
Long-term volatility: 0.4
Seasonal volatility: 32.1
Spot volatility: 0.12
Mean reversion: 0.097 (so annualized is 25)

Clearly I have an issue with the seasonal volatility.
The LT one seems high also compare to the spot one. 

Thanks :)

**Comment by cmdty** [comment]
Those numbers are starting to look better. A few points:
- Annualize the MR by calendar days per year, i.e. 365, as the model simulates every day, rather than just on business days. So that gives you a MR of 35.4 to put into the model.
- You need to annualize the spot vol by mutlplying sqrt of number of business days. This will explain the spot vol looking low compared to the LT vol.
- For Seasonal Vol you need to take the standard deviation of the daily changes in the spread, rather than the spread itself. I did a quick calc of this and it brings the number down.

Once you've got a set up parameters, another thing you can do is to look at what volatility and correlation that they imply using the undocumented helper classes, linked to [here](https://github.com/cmdty/storage#ancillary-python-classes-for-model-covariance-and-spot-simulation).

**Comment by nribei** [comment]
New result, it's better yes :)  : 

Long-term volatility: 0.436
Seasonal volatility: 8.6
Spot volatility: 2.0
Mean reversion: 35.7

When I use that in my storage optimization, I have very high extrinsinc value of course (spot and seasonal volatility are still too high). 

Modified code : 

prix_cal = input_data.parse('Prix CAL')
q1_q3 = input_data.parse('Prix Q1-Q3')
spot = input_data.parse('Prix spot')


q1_q3["daily_changes"] = q1_q3["Q1-Q3"].diff()

seasonal_volatility = np.nanstd(q1_q3["daily_changes"]) * np.sqrt(252) / 0.9

prix_cal["Log_Return_CAL"] = np.log(prix_cal["CAL"] / prix_cal["CAL"].shift(1))
spot["Log_Return_Spot"] = np.log(spot["Spot Price"] / spot["Spot Price"].shift(1))

prix_cal['Log Return'] = np.log(prix_cal['CAL'] / prix_cal['CAL'].shift(1))
long_term_volatility = np.std(prix_cal['Log Return']) * np.sqrt(252)

spot["Adjusted_Log_Spot"] = spot["Log_Return_Spot"] - prix_cal["Log_Return_CAL"]

adjusted_log_month_ahead_price = np.log(spot["Month Ahead Price"].clip(lower=0.0001))

adjusted_log_spot_price_valid = spot["Adjusted_Log_Spot"][np.isfinite(spot["Adjusted_Log_Spot"]) & np.isfinite(adjusted_log_month_ahead_price)]

model = AutoReg(adjusted_log_spot_price_valid, lags=1, exog=adjusted_log_month_ahead_price.loc[adjusted_log_spot_price_valid.index])
results = model.fit()


spot_volatility = np.sqrt(results.sigma2)*np.sqrt(252)
mean_reversion = -results.params[1]*365

print(f'Long-term volatility: {long_term_volatility}')
print(f'Seasonal volatility: {seasonal_volatility}')
print(f'Spot volatility: {spot_volatility}')
print(f'Mean reversion: {mean_reversion}')

**Comment by cmdty** [comment]
I would say that the spot vol you calculated looks OK, but the season vol looks way too big. The paper says _"To derive the winter-summer volatility we use a Q1-forward and a Q3-forward contract. The difference in return between the Q1 and Q3 leads to a series of winter-summer returns."_. So maybe try calculating the seasonal vol by:
- Calculating the log returns for Q1 and Q3 contracts.
- Calculate the spread return as the difference between these 2 series.
- Seasonal vol is then standard deviation of this spread return series * np.sqrt(252)/0.9.

**Comment by nribei** [comment]
It's in fact way better now !

Long-term volatility: 0.43
Seasonal volatility: 0.13
Spot volatility: 2.01
Mean reversion: 35.7

A spot volatility of 2 gives me an extrinsic value 5 times higher that what I should obtain when I value my storage. A SV around 0.4 (with same value of LTV, SVeasonalV, MR) would be more correct. 


Code :
q1_q3['Log_Return_Q1'] = np.log(q1_q3['Q1'] / q1_q3['Q1'].shift(1))
q1_q3['Log_Return_Q3'] = np.log(q1_q3['Q3'] / q1_q3['Q3'].shift(1))


q1_q3['Spread_Return'] = q1_q3['Log_Return_Q1'] - q1_q3['Log_Return_Q3']


seasonal_volatility = np.nanstd(q1_q3['Spread_Return']) * np.sqrt(252) / 0.9

prix_cal["Log_Return_CAL"] = np.log(prix_cal["CAL"] / prix_cal["CAL"].shift(1))
spot["Log_Return_Spot"] = np.log(spot["Spot Price"] / spot["Spot Price"].shift(1))

prix_cal['Log Return'] = np.log(prix_cal['CAL'] / prix_cal['CAL'].shift(1))
long_term_volatility = np.nanstd(prix_cal['Log Return']) * np.sqrt(252)

spot["Adjusted_Log_Spot"] = spot["Log_Return_Spot"] - prix_cal["Log_Return_CAL"]

adjusted_log_month_ahead_price = np.log(spot["Month Ahead Price"].clip(lower=0.0001))

adjusted_log_spot_price_valid = spot["Adjusted_Log_Spot"][np.isfinite(spot["Adjusted_Log_Spot"]) & np.isfinite(adjusted_log_month_ahead_price)]

model = AutoReg(adjusted_log_spot_price_valid, lags=1, exog=adjusted_log_month_ahead_price.loc[adjusted_log_spot_price_valid.index])
results = model.fit()

spot_volatility = np.sqrt(results.sigma2)*np.sqrt(252)
mean_reversion = -results.params[1]*365

**Comment by nribei** [comment]
[data.xlsx](https://github.com/cmdty/storage/files/12701318/data.xlsx)

Sheet "Prix" is my daily forward curve that I use for optimising my storages
Sheet "Prix Q1-Q3" is for the calculation of the spread Q1-Q3 

Thanks !

**Comment by cmdty** [comment]
@nribei I haven't looked at your calibration calculations yet, but I have had a few thoughts on calibration. I don't think calibration purely to historical data in this way is particularly good idea, although it is a good starting point. The final step of the calibration should be to find the model parameters which give a storage valuation which match, or are closest to, published results of storage auctions. Given a set of observed storage PVs (auction results), use a scipy minimiser to find the model parameters which minimises the sum of the squared differences between model PV and observed PV.

Running such a calibration script will obviously take a long time to run, as it's going to have to run the storage model multiple times, but that's fine as it can just be left to run overnight. Ideally the calibration should be performed on a set of storage facilities with diverse characteristics, e.g. fast and slow storage. If it's found that a single set of parameters which give a good fit to diverse storage facilities can't be found, which is might to be the case, the storage faculties being calibrated to should be split into groups with similar characteristics, e.g. fast, medium, slow. Then solve for a different set of model parameters for each storage group.

I would solve for just the spot-factor vol and mean reversion this way, with the long term and season vol being calculated from a historical analysis. That said, even the calculated long term and seasonal vol could still be adjusted based on a fundamental view of past versus future, e.g. if you thing long term vol is going to be higher going forward, than it was in the window of your calibration data, then arbitrarily adjust it up accordingly. Fitting some parameters to historical data, and some to storage PVs might seem odd, but I think it's a practical approach because:
- It acknowledges spot-factor vol and mean are difficult to calibrate historically, as they are the parameter of the spot "factor", rather than the spot price, hence not directly observable and so difficult to accurately calibrate.
- You don't want to solve for too many parameters in minimization as it will make it slow and unstable.
- I think the calculated PV will not be that sensitive to seasonal and long-term vol. It should be more sensitive to spot-factor vol and mean reversion. The relative insensitivity of PV to seasonal and long-term vol will exacerbate the problems in the above point.
- The final step in any calibration should always be to match observed actual storage valuations.

Does this sound like a good idea, and do you have storage auction data to calibrate to?

**Comment by nribei** [comment]
Hello !

I have all the data, I will try to do that !

I am gonna use 5 auctions (1 medium, 1 fast,, 3 slows)

Thanks !

**Comment by cmdty** [comment]
Here's a tip on constructing your penalty function: don't use the difference between outright PV, but PV normalised by storage capacity, ie outright PV divided by capacity, eg storage value in EUR per MWh. This is to ensure that the biggest storage facility doesn't dominate the calibration.

Maybe a further level of normalisation is required to ensure storage with lower extrinsic value per unit capacity don't get underrepresented in the calibration. When calibrating a model to vanilla options, the option PV is generally transformed to implied vol to achieve this, but the same transformation can't be done for storage value. You could try using a penalty function based on the (square of) percentage difference between extrinsic PV per unit capacity of the model and auction results.

**Comment by cmdty** [comment]
@nribei did you manage to get any joy with this calibration approach?

**Comment by nribei** [comment]
Hello !
Yes. 

I used 5 storage options (3 slow, 1 fast, 1 medium). 
Nevertheless I had memory issues (numpy.core._exceptions.MemoryError: Unable to allocate 5.57 MiB for an array with shape (730000,) and data type float64). So I decreased the number of simulations from 2000 to 500 to get a result. 

I didnt do the calibration on all the sets of the storage auctions but one by one, because I think I will have memory issues for sure. (Do you think about a solution ?)

The result I got was ok !
Mean reversion : 35 to 55 (45 in average)
Spot volatility : 0.34 to 0.47 (0.39 in average)
(LT vol = 0.43 and seasonal volatility : 0.13 based on historical)

Here is my code : 
from cmdty_storage import CmdtyStorage, three_factor_seasonal_value, RatchetInterp
import pandas as pd
import xlwings as xw
from openpyxl import load_workbook
import numpy as np
from datetime import date
from scipy.optimize import minimize
import datetime
from dateutil.relativedelta import relativedelta
from scipy.optimize import Bounds

# Define the objective function
def calculate_NPV(params):
    SMR, SV = params
    three_factor_results = three_factor_seasonal_value(
        cmdty_storage=storage_with_ratchets,
        val_date=date.today(),
        inventory=Stockinit,
        fwd_curve=fwd_curve,
        interest_rates=ir_curve,
        settlement_rule=settlement_rule,
        numerical_tolerance=10,
        num_sims=500,
        seed=12,
        spot_mean_reversion=params[0],
        spot_vol=params[1],
        long_term_vol=LTV,
        seasonal_vol=SEV,
        basis_funcs='1 + x_st + x_sw + x_lt + s + x_st**2 + x_sw**2 + x_lt**2 + s**2 + s * x_st',
        discount_deltas=True
    )
    # Compute the differences and return the sum of squared differences
    differences = three_factor_results.npv - observed_NPV
    return np.sum(differences ** 2)


#Recupération des paramètres sur excel
file_path = r"W:\UK\FrontOffice\Marketing Traders\Private\gas optim modele\paramètres.xlsm"
file_path_output = r'W:\UK\FrontOffice\Marketing Traders\Private\gas optim modele\calib result.xlsx'

wb2 = load_workbook(filename = file_path, data_only=True)
wb = xw.Book(file_path)
sheet1 = wb.sheets['Résultat']
sheet2 = wb.sheets['Caractéristiques']

wb1 = load_workbook(filename = file_path, read_only=True)
sheet3 = wb1['Prix']

wb2 = load_workbook(filename = file_path, data_only=True)
sheet_calibration = wb2['Calibration']

#Same for every storages
date_deb = sheet1.range('date_deb').value
date_end = sheet1.range('date_fin').value
Capa = np.array(sheet1.range('capa').value)
LTV = sheet1.range('LTV').value
SEV = sheet1.range('SEV').value
SMR = sheet1.range('SMR').value
SV = sheet1.range('SV').value
Stockinit = sheet1.range('Stockinit').value
IR_rate = sheet2.range('IR_rate').value
date_start = date_deb.date()
date_end = date_end.date()
max_capacite = int(Capa) / (1.0026)

values_gate = sheet2.range('Gate').value
values_gate = np.array(values_gate)
values_gate = [[item.strftime('%Y-%m-%d') if isinstance(item, datetime.datetime) else item for item in sublist] for sublist in values_gate]
date_gate = [sublist[0] for sublist in values_gate]

values_dur = sheet2.range('duration').value
values_reduc = sheet2.range('reduction').value


# Interest Rate
rates = IR_rate
rates_pillars = pd.PeriodIndex(freq='D', data=[date.today(), date.today() + relativedelta(months=1), date.today() + relativedelta(months=3), date.today() + relativedelta(months=6), date.today() + relativedelta(months=12), date.today() + relativedelta(months=24)])
ir_curve = pd.Series(data=rates, index=rates_pillars).resample('D').asfreq('D').interpolate(method='linear')

def settlement_rule(delivery_date):
    return delivery_date.asfreq('M').asfreq('D', 'end') + 20


#Récupération des datas et création des stockages
opt_results = []
compt=-1
for i in range(0, 20, 4):
    compt=1 + compt
    dates = []
    spot_prices=[]
    for row in sheet_calibration.iter_rows(min_row= 2, min_col=1, max_col=1):
        for cell in row:
            dates.append(cell.value)
    for row in sheet_calibration.iter_rows(min_row= 2, min_col=2+compt*3, max_col=2+compt*3):
        for cell in row:
            spot_prices.append(cell.value)

    NPV = sheet_calibration.cell(row=2, column=(3 + compt*3)).value
    storage = int(sheet_calibration.cell(row=4, column=(3 + compt*3)).value)
    print(NPV, storage, type(dates[0]))
    values_dur_inj = values_dur[0][storage * 2]
    values_dur_sout = values_dur[0][storage * 2 + 1]
    values_reduc_niv = [sublist[0] for sublist in values_reduc]
    values_reduc_inj = [sublist[storage * 2 + 1] for sublist in values_reduc]
    values_reduc_sout = [sublist[storage * 2 + 2] for sublist in values_reduc]
    max_injection = max_capacite / (values_dur_inj)
    max_soutirage = -max_capacite / (values_dur_sout)

    # Modélisation des portes
    compteur = 0
    porte_final = []
    porte_int = ()

    for element in date_gate:
        compteur = compteur + 1
        values_gate_min = [sublist[storage * 2 + 1] for sublist in values_gate]
        values_gate_max = [sublist[storage * 2 + 2] for sublist in values_gate]
        num_greater = len([i for i in values_reduc_niv if i <= values_gate_max[compteur - 1]])
        num_smaller = 21 - len([i for i in values_reduc_niv if i >= values_gate_min[compteur - 1]])
        porte_niv = values_reduc_niv[num_smaller:num_greater]
        porte_niv = [i * max_capacite for i in porte_niv]
        porte_inj = values_reduc_inj[num_smaller:num_greater]
        porte_inj = [i * max_injection for i in porte_inj]
        porte_sout = values_reduc_sout[num_smaller:num_greater]
        porte_sout = [i * max_soutirage for i in porte_sout]
        porte_int1 = zip(porte_niv, porte_sout, porte_inj)
        porte_int1 = tuple(porte_int1)
        porte_int1 = list(porte_int1)
        porte_int = (element, porte_int1)
        porte_final.append(porte_int)

    # Ajout fin de porte
        if compteur > 1:
            element1 = (datetime.datetime.strptime(element, '%Y-%m-%d') + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
            porte_niv = values_reduc_niv
            porte_niv = [i * max_capacite for i in porte_niv]
            porte_inj = values_reduc_inj
            porte_inj = [i * max_injection for i in porte_inj]
            porte_sout = values_reduc_sout
            porte_sout = [i * max_soutirage for i in porte_sout]
            porte_int1 = zip(porte_niv, porte_sout, porte_inj)
            porte_int1 = tuple(porte_int1)
            porte_int1 = list(porte_int1)
            porte_int = (element1, porte_int1)
            porte_final.append(porte_int)

    #Création du stockage
    storage_with_ratchets = CmdtyStorage(
        freq='D',
        storage_start=date_deb,
        storage_end=date_end,
        injection_cost=0.00,
        withdrawal_cost=0.00,
        ratchets=porte_final,
        ratchet_interp=RatchetInterp.LINEAR
    )
    #forward curve
    daily_index = pd.period_range(start=dates[0], periods=len(dates), freq='D')
    fwd_curve = pd.Series(data=spot_prices, index=daily_index).resample('D').fillna('pad')

    #Calibration Calcul
    observed_NPV = NPV
    initial_guess = np.array([SMR, SV])
    bounds = Bounds([0, 0], [np.inf, np.inf])
    result = minimize(calculate_NPV, initial_guess, bounds=bounds)
    SMR_opt, SV_opt = result.x




What do you think about it ? 
Thanks a lot

**Comment by cmdty** [comment]
That's a bit strange with the memory. Are you using 32-bit Python? If so, switching to 64-but would help.

**Comment by nribei** [comment]
I am using the 64

**Comment by cmdty** [comment]
From a quick look at your code, apart from it being on the valuation of only a single storage, this approach looks exactly like what I was suggesting. Also, great news that the resulting numbers look sensible.

But the memory problem is concerning, and needs to be fixed because I think 500 is too few simulations, and really the calibration should be performed on more than one storage facility at once.

I think there must be a memory leak. The exception is coming from trying to allocate a 5 MB numpy array which isn't particularly large. After how many iterations of the valuation does this error happen? If it's after the first npv calc it's probably a memory leak. Try running the script and observing the used memory of the process using Windows Task Manager. If you see it consistently increasing then it sounds like a leak.

I won't have time to look at this until the weekend, but I have a few ideas on what can be done. A bit of a long-shot, but try deleting the three_factor_results object using the Python del keyword. You could also try attaching a Python memory profiler to the script to see where the memory is accumulating.

**Comment by nribei** [comment]
[memory_profiler_report.txt](https://github.com/cmdty/storage/files/12827669/memory_profiler_report.txt)
I have generated this file, but not sure it will help you. 

It stops during the calibration of the 3rd storage auction when I use 2000 sims.

**Comment by cmdty** [comment]
@nribei I had a looks at running the calibration code, but couldn't replicate a memory leak, i.e. I couldn't see the memory usage steadily increasing on each evaluation of the objective function. See attached my script:

[main.zip](https://github.com/cmdty/storage/files/12841919/main.zip)

I couldn't rerun exactly the same code that you have, as I can see from the memory profiler report that you are reading stuff in from Excel. Would you be able to post a simplified, but self-contained, Python script which runs the code, but also generated the memory allocation exception?

That said, the implementation of the storage model is not particularly memory efficient, so I've actually published an [alpha version of the cmdty-storage package](https://pypi.org/project/cmdty-storage/1.4.0a1/) which is a _bit_ more efficient. Could you try installing it to see if it runs any better?

pip install cmdty-storage==1.4.0a1

There is a small difference in the way that you need to call the model. First import the type SimulationDataReturned from cmdty_storage, then when calling the valuation function include the new argument sim_data_returned=SimulationDataReturned.NONE. This basically tell the function to include less detailed simulation-level in the returned object, which is fine in your case as you only need the npv. See if running with this version and setting is more reliable with multiple storage and/or higher number of simulations. If this seems to work OK I can publish a proper new version of the package.


A few other points about your calibration code:
- You should probably set the tolerance of the [minimize function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) to be larger than the default, which I imagine is very small. When I was running the calibration, the objective function actually got quite close to a decent calibration, but didn't stop because the default tolerance is too small for this problem, e.g. I think it's ok to stop the minimization if the PVs are within 10 of each other, and probably more.
- As in my attached script above, try printing out some data in the objective function. That way you can see what is going on during the minimization, rather than it being a black box.
- I see you're using a numerical_tolerance of 10, which is very large. Does the storage has step ratchets? You'll see from other issues on here that step ratchets can be hard to get working, and a numerical_tolerance of 10 seems too big, and indicative that something is not quite right with the CmdtyStorage object. If you can post something on here for how this offending storage facility object is created, I might be able to see what the problem is.

**Comment by nribei** [comment]
I created a repo, did you receive the invit ? 
So thats you can access all the files. 

I have done the change in the numerical_tolerance (=1), and i changed the upper bond accordingly. 
It is running right now, but it seems I have still the same issues. 

thanks !

**Comment by cmdty** [comment]
Yes, I got the repo invite and can see the code. It looks like a self-contained example which is exactly what I need to investigate the issue. For completeness can you add a requirements.txt file with the package dependencies?

**Comment by nribei** [comment]
Done !

I can see that with the modification, the script is already much faster :)

**Comment by cmdty** [comment]
What Python version are you using?

**Comment by nribei** [comment]
Python 3.8.10
